# Generated by Django 2.2.27 on 2022-04-25 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='proxy_host',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='代理地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='host',
            field=models.CharField(max_length=100, verbose_name='环境地址'),
        ),
    ]
