# Generated by Django 2.2.27 on 2022-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_auto_20220425_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='proxy_host',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='代理地址'),
        ),
    ]
