# Generated by Django 2.2.27 on 2022-04-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0003_auto_20220425_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='param',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='用户参数'),
        ),
    ]
