# Generated by Django 2.2.27 on 2022-04-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_auto_20220425_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='param',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='用户参数'),
        ),
    ]
