# Generated by Django 2.2.27 on 2022-04-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0005_auto_20220425_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='version',
            field=models.CharField(default='', max_length=10, verbose_name='产品版本'),
        ),
    ]
