# Generated by Django 2.2.27 on 2022-05-05 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0006_host_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='module_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_description',
        ),
        migrations.AddField(
            model_name='module',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='模块描述'),
            preserve_default=False,
        ),
    ]
