# Generated by Django 2.2.27 on 2022-05-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0007_auto_20220505_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='module',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='module',
            name='name',
        ),
        migrations.AddField(
            model_name='module',
            name='index',
            field=models.CharField(default='', max_length=30, verbose_name='路径'),
        ),
        migrations.AddField(
            model_name='module',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='标题名'),
        ),
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='报告名'),
        ),
    ]
